### ISSUE TITLE
IMAP OAuth Authentication (XOAUTH2)

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#1]
Hi,

Is it possible to add XOAUTH2-authentication to the Zend Mail IMAP? See https://github.com/google/gmail-oauth2-tools/issues/18

The [solution](https://github.com/google/gmail-oauth2-tools/blob/master/php/oauth2.php) suggested by Google is not perfect, as it first tries to connect via regular authentication and only after that performs OAuth-authenticaiton.

Here is the implementation of the IMAP OAuth for Zend Mail IMAP: https://github.com/ialert/imap-xoauth2. You just need to add it to your repo.

---

Originally posted by @freescout-helpdesk at https://github.com/zendframework/zend-mail/issues/252

**Comment by francescobianco** [comment]
Hi @weierophinney @EvanDotPro @akrabat I'd start a project to support a full tested version of PHP IMAP library with support for OAUTH. Please take a look to this post https://github.com/ddeboer/imap/issues/443#issuecomment-1172158902

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
