### ISSUE TITLE
Psalm integration

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-mail#113]
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [x] Create a `.psalm.xml.dist` in the project root
- [x] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [x] Run `$ composer require vimeo/psalm`
- [x] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [x] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [x] ~Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`~
- [x] ~Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)~

##### Optional
- [x] Fix as many psalm errors as possible.

**Comment by gennadiylitvinyuk** [comment]
I think composer.lock should be deleted from repository. This is a library at the end...

**Comment by boesing** [comment]
It is, but we decided to have it available for QA checks like codestandard and psalm as these libraries constantly detecting new stuff in newer versions when these are being updated during CI.

So instead of locking these libraries with specific versions we rather want to add `composer.lock` instead.

**Comment by Slamdunk** [comment]
Ok, thanks to @gennadiylitvinyuk the main goals are achieved.
An initial cleanup is still missing tough.

**Comment by boesing** [comment]
@Slamdunk Features are not targeted against Patch releases. Maybe you accidentally added 2.14.1?

**Comment by Slamdunk** [comment]
To me, MINOR releases are for consumer features, not internal improvements ones.
https://github.com/laminas/laminas-mail/pull/147 added zero consumer features, and zero internal improvements, btw.
Right now there are tons of static type bugs that we've drowned into `psalm-baseline`, and if and when someone have the willing to fix them, they'd go into a patch release, not a minor one, wdyt?

**Comment by Ocramius** [comment]
@Slamdunk if it's not a bugfix, it's already into the next minor: chore work is improvement, even if it has little impact downstream :muscle: 

EDIT: to clarify further - only bugfixing in patches, nothing else. Keep patch releases as-stable-as-possible, including potential new artifacts, dev dependencies, etc.

**Comment by Slamdunk** [comment]
Ok then, sorry :pray:

**Comment by Fahl-Design** [comment]
Hi, pslam fails my fix for #162 ( #164 ) on `2.14.x` because `laminas-db` is only suggested in `laminas-validator` package
