### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-mail#114]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by glensc** [comment]
> Modify composer.json to provide support for PHP 8.0 by adding the constraint ~8.0.0

shouldn't this be semver range: `^8.0`?

- [Tilde Version Range (~)](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-)
- [Caret Version Range (^)](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)

**Comment by boesing** [comment]
@glensc We decided to use `~` as PHP does not 100% respect semver. 

https://www.php.net/manual/de/migration71.incompatible.php
https://www.php.net/manual/de/migration72.incompatible.php
https://www.php.net/manual/de/migration73.incompatible.php
https://www.php.net/manual/de/migration74.incompatible.php

**Comment by glensc** [comment]
but then it should be "~7.3.0, ~7.4.0" too? :)

**Comment by boesing** [comment]
@glensc no, because there wont be any new minor in the 7.X series and thus no need to specify these constraints. 

for upcoming versions, we will handle it like this, but for 7.x, nothing will change as of now.
