### ISSUE TITLE
AddressList::addFromString method not fluent

### ISSUE THREAD

**Issue by braindawg** [laminas/laminas-mail#121]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13.x

#### Summary

The docblock for the `AddressList::addFromString` method indicates that it should allow method chaining by returning an `AddressList`, but the method actually returns `void`.

#### Current behavior

`AddressList::addFromString` returns `void`, contrary to its docblock and the behavior of the rest of the state-modifying methods on `AddressList`. Therefore, attempting to chain any `AddressList` class methods after the `addFromString` call results in:

> Error: Call to a member function <chained_method> on null ...

#### How to reproduce

Attempt to chain a call to any `AddressList` method from the result of an `AddressList::addFromString` method, e.g.
`$addressList->addFromString('test@email.com')->has('test@email.com');`

Unit test will be added via a PR shortly.

#### Expected behavior

Per the docblock and the current behavior of all other state-modifying methods (`add`, `addMany`, `merge`), method chaining should work.

**Comment by Ocramius** [comment]
Handled in #123
