### ISSUE TITLE
CHANGELOG missing release 2.12.4

### ISSUE THREAD

**Issue by demiankatz** [laminas/laminas-mail#130]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | current 2.13.x branch

#### Summary

I like to review changelogs when upgrading my dependencies, but there seem to be some issues with the changelog here. I realize this is a somewhat nitpicky problem, but hopefully it is an easy fix, and will reduce confusion for others if it is fixed. Thank you!

#### Current behavior

The changelog shows "TBD" as the release date for 2.12.3, has no 2.12.4 notes at all, and has non-standard formatting for the 2.12.5 release.

#### Expected behavior

I would expect all releases to be listed in the changelog, and for them all to use the same standard format.

**Comment by froschdesign** [comment]
@demiankatz 
You can check the [release notes](https://github.com/laminas/laminas-mail/releases):

* for version 2.12.4: https://github.com/laminas/laminas-mail/releases/tag/2.12.4
* for version 2.12.5: https://github.com/laminas/laminas-mail/releases/tag/2.12.5

The release notes are created automatically via [automatic-releases](https://github.com/laminas/automatic-releases) and based on the issue reports and pull requests for the related milestone.

**Comment by demiankatz** [comment]
Thanks, @froschdesign. Is this a change in policy? I was aware of the GitHub releases page, but in the past, the CHANGELOG.md file often contained more detailed information, so I've historically relied on it. Perhaps it would be helpful to include a link to the GitHub releases at the top of the CHANGELOG.md so those who have formed a habit of looking there can be informed of the new process.

**Comment by glensc** [comment]
The changelogs automation is broken, @Ocramius is aware of it and I think he looked into it, but without final conclusion (the missing changelog was not inserted):
- https://github.com/laminas/laminas-mail/pull/125#issuecomment-752996771

**Comment by froschdesign** [comment]
@demiankatz 
> Is this a change in policy?

Not yet. See: https://github.com/laminas/technical-steering-committee/blob/main/meetings/agenda.md#drop-changelogmd-from-repositories-when-it-leads-to-merge-conflicts

**Comment by demiankatz** [comment]
Great, thank you for all the helpful information and backstory, @glensc and @froschdesign. Please feel free to close this issue if you feel it is unnecessary to keep open -- I'm satisfied that I understand the situation, and it sounds like the overall solution is going to be bigger than one issue in one repository. :-)

**Comment by Slamdunk** [comment]
Changelog is now kept only within Github releases page
