### ISSUE TITLE
Remove `--ignore-platform-reqs` flag from `composer install` in CI when running on PHP 8

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-mail#131]
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#117 introduces a `--ignore-platform-reqs` flag when running in CI with PHP 8 (https://github.com/laminas/laminas-mail/pull/117#discussion_r564506102): we should get rid of that flag as soon as all dependencies are up to date.

**Comment by Slamdunk** [comment]
Some clever guy made `Laminas CI workflow` which is now merged here, this issue is superseded.
