### ISSUE TITLE
[RFC]: Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by glensc** [laminas/laminas-mail#133]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | x.y.0  |
| BC Break?           | Yes/No |

### Goal

Seems Travis integration is broken: Travis CI jobs not tied to PR any more. They are probably not even executed.

**Comment by glensc** [comment]
As it seems Travis integration is broken, and likely more and more problems appear from using it, is there coordinated plans across laminas projects to move to GitHub actions? Or you'll be just accepting PR's on the go? If so, are some projects already migrated? Example PR's then to get started easier.

**Comment by Ocramius** [comment]
Migration to github actions is part of the TSC discussions next week: https://github.com/laminas/technical-steering-committee/blob/main/meetings/agenda.md#adopt-the-proposed-github-actions-workflow
