### ISSUE TITLE
Headers#has() can return true when it should return false

### ISSUE THREAD

**Issue by Zenexer** [laminas/laminas-mail#152]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | HEAD (2.15.x)

#### Summary

`Laminas\Mail\Headers#has()` will return `true` for some values when it should return `false`

#### Current behavior

If a `Headers` instance contains a header with key `'00'`, `$headers->has('00000')` will return `true`.

#### How to reproduce

```php
$headers = new Headers();
$headers->addHeaderLine('0', 'test');
$headers->addHeaderLine('1', 'test');

var_export($headers->has('00000'));  // true
echo PHP_EOL;
var_export($headers->has('00001'));  // true
```

#### Expected behavior

```php
$headers = new Headers();
$headers->addHeaderLine('0', 'test');
$headers->addHeaderLine('1', 'test');

var_export($headers->has('00000'));  // false
echo PHP_EOL;
var_export($headers->has('00001'));  // false
```

**Comment by Xerkus** [comment]
This is an egde case coming from the fact that php converts numeric strings in array keys to integers. It is a won't fix on php bug tracker and there is no practical alternative to php arrays.

There are no valid numeric headers in use, afaik, and for the reason above this one is likely to stay a won't fix.

**Comment by glensc** [comment]
To my knowledge PHP 8.0 changed the behavior on this, so it's fixed with PHP 8.0, also, I believe enabling strict mode will also make compares strict.

**Comment by Xerkus** [comment]
@glensc  https://3v4l.org/NBsYl No it didn't. It is still a major headache with strict types enabled with keys changing type.

However, I see that `0000` or `0001` does not change, so this is unrelated non-strict comparison bug here that is actually fixable.

**Comment by Zenexer** [comment]
@glensc I'm testing exclusively with PHP 8.0.5 and strict mode enabled.

**Comment by Zenexer** [comment]
Also, this is a pretty easy fix: just pass `true` as the third parameter to `in_array`.

**Comment by Zenexer** [comment]
Ignore that commit; I'm working on a properly-signed PR with unit tests.
