### ISSUE TITLE
No connection via IMAP / Mail recieving

### ISSUE THREAD

**Issue by kilixn** [laminas/laminas-mail#156]
Hey there,

I'm working on a webmail program and want to use laminas-mail to display the mails.
I wrote a test program : 

```php
use Laminas\Mail\Storage\Imap;

echo "test";

// Connecting with Imap:
$mail = new Imap([  
    'host' => 'mail.domain.com',
    'user' => 'user1',
    'password' => 'passw0rrd',
    'novalidatecert' => true,
]);

$messageNum = 1;

$message = $mail->getMessage($messageNum); //messageNum is mail number ($message_id)


// get content-type header
$type = $message->contentType;


// output message content for HTML
echo '<pre>';
echo $message->getContent();
echo '</pre>';
```

And installed it via composer at /html where the PHP file is.

The only thing that is displayed is the "test". And there is no "feedback" or displaying any information on the laminas / Imap connection.
The logs of IMAP don't show any connection.

Just wanted to ask if anyone has an Idea ?

**Comment by dennybrandes** [comment]
try to enable error messages. Just add at line 2:
error_reporting(-1);
ini_set('display_errors', 1);
