### ISSUE TITLE
Error 500 with uncaught Laminas\Mail\Protocol\Exception\RuntimeException

### ISSUE THREAD

**Issue by rarog** [laminas/laminas-mail#158]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14.1

#### Summary

I get the error despite trying to catch the most generic Mail RuntimeEception when SMTP password is wrong.

#### Current behavior

[Thu Jun 17 23:36:56.305549 2021] [php7:error] [pid 18844] [client 127.0.0.1:55284] PHP Fatal error:  Uncaught Laminas\\Mail\\Protocol\\Exception\\RuntimeException: Could not read from smtp.aol.com in /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:309\nStack trace:\n#0 /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php(338): Laminas\\Mail\\Protocol\\AbstractProtocol->_receive()\n#1 /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(461): Laminas\\Mail\\Protocol\\AbstractProtocol->_expect()\n#2 /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(500): Laminas\\Mail\\Protocol\\Smtp->quit()\n#3 /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(488): Laminas\\Mail\\Protocol\\Smtp->_disconnect()\n#4 /var/www/html/xxx/vendor/laminas/laminas-mail/src/Transport/Smtp.php(188): Laminas\\Mail\\Protocol\\Smtp->disconnect()\n#5 [internal function]: Laminas\\Mail\\Transport\\Smtp->__destruct()\n#6 {main}\n  thrown in /var/www/html/xxx/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php on line 309, referer: http://localhost/xxx

#### How to reproduce

```php
            try {
                // $transport is of type Laminas\Mail\Transport\Smtp
                // $message is of type Laminas\Mail\Message
                $transport->send($message);
                return true;
            } catch (\Laminas\Mail\Exception\RuntimeException $e) {
                return false;
            }
```

#### Expected behavior

As Laminas\Mail\Protocol\Exception\RuntimeException is derived from Laminas\Mail\Exception\RuntimeException I would expect my code to continue without error 500, as I'm trying to catch the most generic exception of Laminas\Mail, but I don't seem to be able to catch it in proper way.

**Comment by rarog** [comment]
It seems, that a connection error that otherwise would be caught by by the catch block will raise another error, when the object is destroyed and trying to disconnect. So far I found a workaround, that isn't beautiful and should either be fixed during destruction or otherwise be documented.

```php
        // $transport is of type Laminas\Mail\Transport\Smtp
        // $message is of type Laminas\Mail\Message
        try {
            try {
                $transport->send($message);
                return true;
            } catch (\Laminas\Mail\Exception\RuntimeException $e) {
                return false;
            }
        } finally {
            try {
                unset($transport);
            } catch (\Laminas\Mail\Exception\RuntimeException $e) {
                // Trying to work around problem described in https://github.com/laminas/laminas-mail/issues/158
            }
        }
`

**Comment by Slamdunk** [comment]
See:

1. https://docs.laminas.dev/laminas-mail/transport/smtp-authentication/#smtp-transport-usage-for-servers-with-reuse-time-limit (https://github.com/zendframework/zend-mail/pull/117)
1. https://github.com/Slamdunk/zend-mail-extensions/blob/master/lib/Protocol/TimeKeeperSmtpProxy.php
