### ISSUE TITLE
Docs Fix: Add in the required type for the content part

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#16]
The current documentation is missing this crucial requirement for the multipart/alternative + attachments section.

This had me stumped for a long time and I finally found the solution here:
https://akrabat.com/sending-attachments-in-multipart-emails-with-zendmail/

Note that the \n character is not necessary (and I think in some clients causes errors).

---

Originally posted by @internalsystemerror at https://github.com/zendframework/zend-mail/pull/228

**Comment by samsonasik** [comment]
this seems already in the doc https://docs.laminas.dev/laminas-mail/message/attachments/#multipartalternative-emails-with-attachments

I am closing it.
