### ISSUE TITLE
[BUG] [PHP8] "Sendmail" Transport - Mailencoding is broken after php core fixes

### ISSUE THREAD

**Issue by Fahl-Design** [laminas/laminas-mail#162]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14.X + 2.15.X
| PHP |  >= 8.0

#### Summary

PHP Core fixed a bug in php ( https://bugs.php.net/bug.php?id=47983 ) which expectes mail content to contain CRLF line endings 

#### Current behavior

https://github.com/laminas/laminas-mail/blob/ee318f54ca9d9d475acfea074e8077e56c5198bc/src/Transport/Sendmail.php#L123-L128

Line endings are filtered

more infos on topic: https://github.com/PHPMailer/PHPMailer/pull/2188

#### How to reproduce

Send an HTML email with `sendmail` transport with PHP 7 and PHP 8 and see the PHP 8 versions is broken because it can't be parsed and is detected as `Content-Type: text/plain`

#### Expected behavior

https://github.com/laminas/laminas-mail/blob/ee318f54ca9d9d475acfea074e8077e56c5198bc/src/Transport/Sendmail.php#L123-L128

don't replace `"\r\n"` with `"\n"`

#### Fix:

remove the replaces (PR is #164  )

**Comment by weierophinney** [comment]
Fixed with 2.14.2.
