### ISSUE TITLE
When set -f option, no set -f option automatically

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#17]
`Zend\Mail\Transport\SendMail` always append envelope-from parameter.  
But I want to set any envelope-from.  
In this PR, only when not set option `-f`, set `-f` option automatically.
This means if I set `-ffoo@example.com` or `-bs -ffoo@example.com`, `Zend\Mail\Transport\Sendmail` doesn't set `-f` option.

---

Originally posted by @tzmfreedom at https://github.com/zendframework/zend-mail/pull/227

**Comment by weierophinney** [comment]
without getting deeper to the actual changes, have some thoughts:

1. seems weird to have a negative parameter. how about set positive parameter which is b default true, and can be set as false. 
2. maybe have a specific option (envelope related) rather generic "no override" as behavior could be different if want/want not to override some other parameter.

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/227#issuecomment-503043802

**Comment by weierophinney** [comment]
Thank you for you reply and advice !

I rethink, revise my code and changed this PR goal. 

On this PR, only when not set option `-f`, set `-f` option automatically.  
This means if I set `-ffoo@example.com` or `-bs -ffoo@example.com`, Transport\Sendmail doesn't set `-f` option.  
So there is no negative parameter, no additional method.  

---

Originally posted by @tzmfreedom at https://github.com/zendframework/zend-mail/pull/227#issuecomment-503537825

**Comment by weierophinney** [comment]
you should update PR title as well. and the body is a bit hard to read as well.

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/227#issuecomment-503611509

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-mail/pull/104 for it

**Comment by tzmfreedom** [comment]
@samsonasik Thank you!!
