### ISSUE TITLE
Treat quote as value if already in quote using another delimiter

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#18]
Fixes the issue as described in #222.

---

Originally posted by @silvadiego at https://github.com/zendframework/zend-mail/pull/226

**Comment by weierophinney** [comment]
@silvadiego is this same problem? can you cherry-pick testcase from there?

- https://github.com/zendframework/zend-mail/pull/224

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/226#issuecomment-474120907

**Comment by weierophinney** [comment]
not sure, should https://github.com/zendframework/zend-mail/pull/224 be added to changelog too? but at least include https://github.com/zendframework/zend-mail/pull/222 in changelog!

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/226#issuecomment-475211421

**Comment by weierophinney** [comment]
@weierophinney can we get this merged? 

as noted in https://github.com/zendframework/zend-mail/pull/224, this is regression from changes from https://github.com/zendframework/zend-mail/pull/147 resolution i.e from your https://github.com/zendframework/zend-mail/commit/8aac5f7b4d354ea65128be6d2134d4648f47286d commit

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/226#issuecomment-488811597

**Comment by weierophinney** [comment]
@Xerkus ping?

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/226#issuecomment-508891226

**Comment by weierophinney** [comment]
@silvadiego I don't know what's this project merge policy (hardly anybody accepts changes here), but good practice is to squash useless commits to one commit and `git push -f` (three commits altering changelogs could be squashed)

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/226#issuecomment-509268974

**Comment by glensc** [comment]
@weierophinney please edit issue body to fix ticket link
