### ISSUE TITLE
Laminas-mail : running behind  Proxy

### ISSUE THREAD

**Issue by EC2311** [laminas/laminas-mail#186]
Hello

We use a product which uses laminas-mail.
This product is configured with a proxy to reach internet : ok

We don't succeed to use laminas-mail with the proxy. 
I tried to update the protocoltrait.php , But I don't suceed
![image](https://user-images.githubusercontent.com/42341169/166683309-86c21c46-b7ed-4817-9865-c3b168995a5d.png)

![image](https://user-images.githubusercontent.com/42341169/166683916-8592c4c1-45de-493a-ae64-70649a5034e2.png)

How to run laminas-mail behind a proxy ?
Thanks
Best regards

**Comment by EC2311** [comment]
Hello

Nobody has this problem neither a solution/help ?
Thanks
Best regards

**Comment by froschdesign** [comment]
@EC2311 
> Nobody has this problem…

I don't have the problem and unfortunately don't know any solution. Please try to ask in the [chat](https://getlaminas.org/participate/).

**Comment by EC2311** [comment]
hello @froschdesign 

OK, so how can I find the real problem, if it's not linked to firewall ?
I can access to outlook.office365 using navigator on the server, so for me firewall rules are ok... but perhaps not fully ? 

what are yours advises ?

**Comment by Ocramius** [comment]
Closing here: this issue is not related with this package, but rather with your network setup.

You should probably just allow outbound traffic on port 993.
