### ISSUE TITLE
Doc sending-multiple-mails example error

### ISSUE THREAD

**Issue by bouks** [laminas/laminas-mail#189]
### Bug Report

Documentation issue

#### Summary

The example https://docs.laminas.dev/laminas-mail/transport/smtp-multiple-send/#sending-multiple-mails-per-smtp-connection_1
Should replace recipient instead of accumulate them in the "To" header.

#### Current behavior
It adds recipient.

**`$message->addTo($address);`**

So, if 10 recipients, the first recipient, for example, will receive 10 times the email.

```
foreach ($recipients as $address) {
    // Clone the message and add a recipient:
    $message = clone $template;
    $message->addTo($address);

    $transport->send($message);
}
```

#### Expected behavior
Replacing recipient.

**`$message->setTo($address);`**

```
foreach ($recipients as $address) {
    // Clone the message and add a recipient:
    $message = clone $template;
    $message->setTo($address);

    $transport->send($message);
}
```
#### About cloning
In this example cloning is not useful.

So, the best and simple example is:

```
use Laminas\Mail\Message;
use Laminas\Mail\Transport\Smtp;

// Create transport
$transport = new Smtp([
    'host' => 'mail.example.com'
]);

// Create a base message:
$message = (new Message()) // to doc reviewer : since PHP 5.4
                ->addFrom('sender@example.com', 'John Doe')
                ->addReplyTo('replyto@example.com', 'Jane Doe'
                ->setSubject('Demo of multiple mails per SMTP connection')
                ->setBody('... Your message here ...');

// Loop through recipients:
foreach ($recipients as $address) {
    $message->setTo($address);
    $transport->send($message);
}
```

**Comment by Ocramius** [comment]
Hey, could you send a patch to change the docs directly? It's this document in this repo: https://github.com/laminas/laminas-mail/blob/2.17.x/docs/book/transport/smtp-multiple-send.md

**Comment by bouks** [comment]
@Ocramius 
Done. :) 

https://github.com/laminas/laminas-mail/commit/8527a05fe5102572544a262bfa8d2ae8df14e67b

**Comment by bouks** [comment]
@Ocramius 
Sorry, i forgot to remove 
` // to doc reviewer : since PHP 5.4`
