### ISSUE TITLE
Support to add or remove flag(s) on a message

### ISSUE THREAD

**Issue by jbostoen** [laminas/laminas-mail#205]
### Feature Request

Allow this method to specify which flags need to be added or removed:
https://github.com/laminas/laminas-mail/blob/bf7504247d5a110d941efa8eb4815f5292a8dc56/src/Storage/Imap.php#L550

It seems to be available through the storage, but not on the message? Is this a limitation or just not implemented (yet) for some reason?

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Allow this method to specify the mode:
https://github.com/laminas/laminas-mail/blob/bf7504247d5a110d941efa8eb4815f5292a8dc56/src/Storage/Imap.php#L550

It seems to be available through the protocol's `store()` method, but not directly on the message? Is this a limitation or just not implemented (yet) for some reason?

**Comment by jbostoen** [comment]
I dug around a bit and stumbled upon this comment: https://github.com/laminas/laminas-mail/issues/179#issuecomment-1085521057

Is there a reason the "protocol" is protected? If so, would a PR be accepted which introduces this `getProtocol()` method natively? Or is even in the long term the only proper way to go to create a custom class?

**Comment by Ocramius** [comment]
In general, exposing internals increases the API surface, and therefore removes flexibility in upgrade/refactoring and increases the likeliness of breaking changes.

What is the use-case for exposing `getProtocol()`?

**Comment by jbostoen** [comment]
I'm porting some code which was using a different IMAP implementation that didn't support OAuth 2.0. There, in some cases, it turned out the IMAP "deleted" flag was accidentally set.

So before processing this IMAP folder, I just added a bit of code which removed the "delete" flag. Basically it would do the opposite of this method: https://github.com/laminas/laminas-mail/blob/bf7504247d5a110d941efa8eb4815f5292a8dc56/src/Storage/Imap.php#L281 

The legacy implementation relies on this native PHP method: https://www.php.net/manual/en/function.imap-undelete.php

**Comment by Ocramius** [comment]
Well, the protocol is given at creation time, so you should be able to get an instance without asking it to the storage:

https://github.com/laminas/laminas-mail/blob/fe1ac4aa49b1971e4dac9e1bfc1c4d11e6aeba10/src/Storage/Imap.php#L201-L206

The fact that `Storage\Imap` also creates a protocol (shady - old way of doing things :-( ) is kinda secondary, I'd say:

https://github.com/laminas/laminas-mail/blob/fe1ac4aa49b1971e4dac9e1bfc1c4d11e6aeba10/src/Storage/Imap.php#L221-L235

My endorsement would be to create the protocol upfront, then keeping a reference to it when you need it: this also removes a lot of responsibilities from `Storage\Imap` (reads: less space for it to mess it up :D )

Sadly, we can't change that constructor anymore: too many BC implications.

**Comment by jbostoen** [comment]
Thanks for your time and detailed explanation!

So the best workaround is like the one in the comment I linked to earlier?

**Comment by Ocramius** [comment]
I think the best workaround would be to operate on the protocol itself, before passing it to the storage: is that workable?

**Comment by jbostoen** [comment]
Thanks for the advice, but for now it would be too complicated. Currently trying to make the replacement as much "drop in" as possible rather than revising the entire logic :)

**Comment by Ocramius** [comment]
Two workarounds endorsed:

 1. using reflection (ugly, but will get you there, for now)
 2. extending the storage to make the transport available

The correct solution is having the transport upfront, but these should work.

Meanwhile, closing as "won't fix" here.
