### ISSUE TITLE
PHP Fatal error:  Cannot use ::class with dynamic class name in /home/magento/web/magento2.perfectmakeupmirrors.com/public_html/vendor/laminas/laminas-mail/src/Message.php on line 394

### ISSUE THREAD

**Issue by pramodraam** [laminas/laminas-mail#210]
When I ran the command php bin/magento s:s:d -f while upgrading Magento from 2.4.2 to 2.4.4, I get the following error.

PHP Fatal error:  Cannot use ::class with dynamic class name in /home/magento/web/magento2.perfectmakeupmirrors.com/public_html/vendor/laminas/laminas-mail/src/Message.php on line 394

Please help me fix this.

**Comment by gsteel** [comment]
Some information about the version of PHP you are running and the version of `laminas/mail` that you have installed would be useful

**Comment by Ocramius** [comment]
This project rewuires PHP 8.0 or 8.1 in order to work, starting from `2.17.0`:

https://github.com/laminas/laminas-mail/blob/bf7504247d5a110d941efa8eb4815f5292a8dc56/composer.json#L11

You probably ran `composer update` on a PHP version incompatible with your deployment environment.

Closing here.

**Comment by pramodraam** [comment]
Thanks, Please let me know what you mean by "deployment environment" in
your comment.?

**Comment by benlau87** [comment]
@pramodraam Hey, were you able to fix this issue?

**Comment by samsonasik** [comment]
You may have diffrerent php version between cli and web, update all to php 8+
