### ISSUE TITLE
Broken Content-Type header value with a new-line

### ISSUE THREAD

**Issue by speller** [laminas/laminas-mail#211]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.17.0

#### Summary

Broken Content-Type header value with a new-line

#### Current behavior

Header value is added to the mail with a new-line:

```none
Content-Type: text/html;
 charset="utf-8"
```

#### How to reproduce

Add the content-type header with encoding

#### Expected behavior

```none
Content-Type: text/html; charset="utf-8"
```

**Comment by Xerkus** [comment]
This is not a bug and a valid folded header representation.

See:
https://www.rfc-editor.org/rfc/rfc822#section-3.1.1
https://www.rfc-editor.org/rfc/rfc2822#section-2.2.3
https://www.rfc-editor.org/rfc/rfc5322#section-2.2.3

It is not an invalid behavior but somewhat unexpected for such a short line.

**Comment by speller** [comment]
OK, thank you for the clarification
