### ISSUE TITLE
Email with special character

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#22]
zend-mail:2.5.2
vendor/zendframework/zend-mail/src/Header/HeaderValue.php:112
method `Zend\Mail\Header\HeaderValue::assertValid($value)` throws RuntimeException - Invalid header value detected validation e-mail:   ً zel10@yandex.by. Please pay attention that email contains symbol https://en.wiktionary.org/wiki/%D9%8B. But zend-validator EmailAddress considered this email valid. I can not understand which side of the error

---

Originally posted by @r-erema at https://github.com/zendframework/zend-mail/issues/221

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
