### ISSUE TITLE
Pass SMTP server response code to Runtime Exception

### ISSUE THREAD

**Issue by wilfriedwolf** [laminas/laminas-mail#236]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    |no

#### Summary

It would be quite useful to pass the response code to the Exception in 

\Laminas\Mail\Protocol\AbstractProtocol::_expect

Would be pretty easy:
```php
diff --git a/src/Protocol/AbstractProtocol.php b/src/Protocol/AbstractProtocol.php
--- a/src/Protocol/AbstractProtocol.php	
+++ b/src/Protocol/AbstractProtocol.php
@@ -352,7 +352,7 @@
         } while (str_starts_with($more, '-'));
 
         if ($errMsg !== '') {
-            throw new Exception\RuntimeException($errMsg);
+            throw new Exception\RuntimeException($errMsg, $cmd);
         }
 
         return $msg;
```

**Comment by Slamdunk** [comment]
It's interesting: can you propose a Pull Request with the change and a test supporting it?

**Comment by schnumsel** [comment]
Hi @Slamdunk 

I am @wilfriedwolf  in private ;)  
The PR was rejected, because of some stuff I do not understand by now, maybe you can help me? Best Regards ,

Willi

**Comment by Ocramius** [comment]
It wasn't rejected: there are a number of CI-detected problems in #237.

Please read through the failures and attempt to get rid of them, then push to the same branch 👍

**Comment by schnumsel** [comment]
Ah ok @Ocramius 

I saw an error because I did not sign the commit, which I did not know up to now, you can do. Anyhow, I'll try to get rid of the errors (which I did not see up to now)

Best regards,

Willi

**Comment by schnumsel** [comment]
@Ocramius @Slamdunk No idea, why my commits are still failing: see comment here: https://github.com/laminas/laminas-mail/pull/237#issuecomment-1553712336
