### ISSUE TITLE
Current Updates in ServiceManager break Tests

### ISSUE THREAD

**Issue by schnumsel** [laminas/laminas-mail#239]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | branch 2.23.x

#### Summary

When trying to create a PR for branch 2.23.x, the tests fail because of a  [BC break in ServiceManager 3.21](https://github.com/laminas/laminas-servicemanager/pull/184/files#diff-5470c7fee9ea3d84104b00ba271bfd93257384018f64b1a57e8105fc8b06ea2d).
This is because some of the tests (fixed) run on SM v3.20 and others (latest) run on SM v3.21 which are not compatible.

#### Current behavior
Tests executed after a PR is done fail because of this BC break.

#### How to reproduce
Change anything irrelevant to tests in current 2.23.x branch.

#### Expected behavior
Tests pass

#### See also

- https://github.com/laminas/laminas-mail/pull/238
- https://github.com/laminas/laminas-mail/pull/237

**Comment by Slamdunk** [comment]
Fixed in https://github.com/laminas/laminas-mail/pull/233
