### ISSUE TITLE
Update documentation about dependency ServiceManager

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#24]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-mail/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mail/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Using the most complete version of the component with SmtpOptions and SmtpTransport a dependency error is reported and in relation to this has already been discussed previously.

[problem and solution #62](https://github.com/zendframework/zend-mail/issues/62)

But the documentation is not good for this use.

I suggest that in these two links be informed about the dependency:

(1) https://docs.zendframework.com/zend-mail/transport/smtp-authentication/#smtp-authentication
(2) https://docs.zendframework.com/zend-mail/transport/smtp-options/

---

Originally posted by @eduardobona at https://github.com/zendframework/zend-mail/issues/219

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
