### ISSUE TITLE
Return-Path Email is not used

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#27]
## Description 

E-mail Return-Path is not set correctly because it only uses the last forced e-mail address, so as workaround I implemented this code change to give priority to the e-mail address that is already stored in the parameters and therefore the return path mail will be set correctly.

E.g. $parameters = " '-f test1@mail.com' '-f test2@mail.com'";
It will use 'test2@mail.com' as return path email.

## Magento 2.3.0 Alpha: steps to reproduce
     1 - Admin store: Stores > Settings > Configuration > Advanced > System > Mail Sending Settings > Return-Path Email - set a different return path email
     2 - Place an order
     3 - Look for ´Return-Path: <new return path email>' in the email

---

Originally posted by @Filipe-Bicho at https://github.com/zendframework/zend-mail/pull/215

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
