### ISSUE TITLE
PHP 8.4

### ISSUE THREAD

**Issue by xvilo** [laminas/laminas-mail#270]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

I've read this package is abanoded, due to nature of our codebase we can not yet easily migrate away from this package. It seems the allowed PHP version constraints are set very strict. Two questions:
- Can we still add PHP 8.4 support to this package?
- Can we relax the PHP version constraint to `^8.1` instead, so we can more easily try and keep using this within the PHP 8 releases in the future? (Would not need any more yearly PR's)

**Comment by froschdesign** [comment]
@Slamdunk 
It is your decision.

---

> * Can we relax the PHP version constraint to `^8.1` instead, so we can more easily try and keep using this within the PHP 8 releases in the future? (Would not need any more yearly PR's)

This is against our guidelines and will not work, because nobody knows what backward compatibility breaks PHP will bring in with the next minor release. [PHP does not follow semantic versioning!](https://www.php.net/releases/8.4/en.php#deprecations_and_bc_breaks)

**Comment by Slamdunk** [comment]
Package is abandoned, sorry.

@froschdesign can you archive the entire repo please? I don't have the permission to do that.

**Comment by froschdesign** [comment]
@Slamdunk 
This requires some preparatory work. See: https://github.com/laminas/.github/pull/51

**Comment by xvilo** [comment]
So ~two months before a new release it's marked as abandoned? Would have rather seen this happen just after. Means we can't upgrade the codebase to PHP 8.4 at this point. 

I had hoped laminas would have provided some more stability, but that isn't possible this way. 

> This is against our guidelines and will not work, because nobody knows what backward compatibility breaks PHP will bring in with the next minor release. [PHP does not follow semantic versioning!](https://www.php.net/releases/8.4/en.php#deprecations_and_bc_breaks)

I am aware of this, but that would then be up to the end users especially after it's abandonment. Doing this would increase its life span a slight bit and would give the end users some more ease into migrating away. 

Is there no possibility to have this?

**Comment by Slamdunk** [comment]
> Is there no possibility to have this?

Yes, you can either:

1. Fork the project, apply the patch you need and use it
2. Or ask Laminas for a quote on your needs

**Comment by froschdesign** [comment]
> So ~two months before a new release it's marked as abandoned? Would have rather seen this happen just after. Means we can't upgrade the codebase to PHP 8.4 at this point.

Not two months, but since 4 December 2023, so this is not true:

> I had hoped laminas would have provided some more stability, but that isn't possible this way.

**Comment by froschdesign** [comment]
@xvilo 
There is an overview for this: [Current Maintenance Status of Laminas & Mezzio Packages](https://getlaminas.org/packages-maintenance-status/)

**Comment by xvilo** [comment]
> > Is there no possibility to have this?
> 
> Yes, you can either:
> 
> 1. Fork the project, apply the patch you need and use it

Yes, keeping up another fork next to our zend 1 fork. We tried moving away from that by using Laminas, but apparently we need to fork that too now.

> 2. Or ask Laminas for a quote on your needs

That is absolutely not needed, I would be able to help out to add PRs tho

> > So ~two months before a new release it's marked as abandoned? Would have rather seen this happen just after. Means we can't upgrade the codebase to PHP 8.4 at this point.
> 
> Not two months, but since 4 December 2023, so this is not true:

Well, it was marked as such in September this year https://github.com/laminas/laminas-mail/pull/269/files so its not weird I think differently of this. 

Thanks for the overview, but as soon as the status changes there it should better reflect this on the package itself, as that was not clear to me. I hope you can imagine that signalling it this way will not reach a lot of people until you set it to abandoned.

Thanks anyway, its unfortunate the abandoment was not clearer to me at an earlier stage.

**Comment by froschdesign** [comment]
@xvilo 
> Yes, keeping up another fork next to our zend 1 fork. We tried moving away from that by using Laminas, but apparently we need to fork that too now.

Please have a look in the forum, where some forks are listed and which ones are actively maintained: https://discourse.laminas.dev/t/zf1-community-maintained-official-fork/419/37
And allowing new versions here does not help if errors occur with version 8.4, 8.5 or 8.6. How are these supposed to be fixed? A fork is therefore the right way.

**Comment by xvilo** [comment]
I believe you’re looking at it from a different perspective that doesn’t help people in general and that’s a shame. 

For now I know enough and this issue can exist as of why and what the options are for others in the future.

**Comment by froschdesign** [comment]
@xvilo 
You are overlooking a crucial point here: we work on all these components in our free time, without pay!
And the problem here is laminas-mime:

> Aleksei pointed out that MIME has evolved over time, and we are quite behind. On top of that, in his research, he discovered that the Thunderbird email client as 3 separate MIME parser implementations, due to the amount of different mail out there, which may or may not conform to different MIME-related RFCs. His take is that it would be massive work to keep our own package up-to-date and secure. Filippo seconded this, pointing out that zbateson/mail-mime-message (which he helps maintain) is very careful to point out that it can parse the message structure, but it's up to the person using the library to actually do something useful with it (which might include transforming it based on encoding). Aleksei came back to point out that UTF-8 encoded subjects is one modern MIME capability we do not support, and these are very common today.

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2023-12-04-TSC-Minutes.md#maintainers-for-laminas-mime-and-laminas-mail

Of course, it is a sad decision to discontinue a component, but unfortunately, we are also struggling with the typical problem of open source: there is very little help.
