### ISSUE TITLE
getFolders() gives Maximum execution time exceeded

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#29]
I am getting "Maximum execution time exceeded" when i try to do $mail->getFolders().

---

Originally posted by @canaan5 at https://github.com/zendframework/zend-mail/issues/210

**Comment by weierophinney** [comment]
Could be related to #191 and #240 

---

Originally posted by @jensstalder at https://github.com/zendframework/zend-mail/issues/210#issuecomment-525327167

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
