### ISSUE TITLE
Zend\Mail\Message::addFrom expects a string, AddressInterface, array, AddressList, or Traversable as its first argument; received "NULL"

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#3]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-mail/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mail/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
```

### Actual results

---

Originally posted by @gntlby at https://github.com/zendframework/zend-mail/issues/250

**Comment by weierophinney** [comment]
@gntlby 
Thank you for opening this report. To reproduce the problem please add a detailed description or create a pull request with an unit test which illustrates the problem.

Thanks in advance!

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-mail/issues/250#issuecomment-559967195

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
