### ISSUE TITLE
How to migrate from Zend 1.0??? 

### ISSUE THREAD

**Issue by UBAazubi** [laminas/laminas-mail#32]
Hey,
I don't know what to do. My boss told me to migrate our Zend 1 applications to current Zend-Mail (or Laminas) without touching any source code (because this would be too much work). Maybe with a wrapper-class or whatever... In the best case we would like to migrate to composer as well but that seems to be too difficult without touching projects.

Our folder looks like this
- Project X
   ->src
- Project X2
   ->src
- Project X3
   ->src
- Zend-Mail-Framework

Maybe you've got an idea. Our version is round'about November 2011?!?

Thanks anyway
~Tim

**Comment by Xerkus** [comment]
Issue tracker is for reporting issues or requesting features for the package. For support please use our [Slack chat](https://laminas.dev/chat/#slack) and [forums](https://discourse.laminas.dev)

**Comment by UBAazubi** [comment]
![Q6hVzjl](https://user-images.githubusercontent.com/57992054/72459615-7475fe00-37cb-11ea-88e9-c808f4f6dadc.png)

**Comment by geerteltink** [comment]
@UBAazubi  If you open an issue with that button it also says:

> Before asking question here, please try asking in our chat (https://laminas.dev/chat)
> or forums (https://discourse.laminas.dev).
> 
> Keep in mind that GitHub is primarily an issue tracker.

**Comment by Xerkus** [comment]
@UBAazubi we did not accept usage questions on issue trackers before as it generates significant amount of notification noise. I will need to check if we revised that recently or if, more likely, Support Question is misleading and need to be amended.

In the meanwhile I recommend to use our forums as this question is not entirely within the scope of this package.
