### ISSUE TITLE
replace call_user_func* with self invoked function

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#34]
as dev-master already use php ^7.1

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mail/pull/200

**Comment by michalbundyra** [comment]
I rolled back the changes on master that changed the PHP minimum, as we are not supposed to do that in a minor release. 2.10.0 will support 5.6 and 7.0 again.

As such, marking this for 3.0.0.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mail/pull/200#issuecomment-395213765

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-mail. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-mail to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-mail.
 - In your clone of laminas/laminas-mail, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mail/pull/200#issuecomment-569994623

**Comment by samsonasik** [comment]
i created PR https://github.com/laminas/laminas-mail/pull/101 for it.

**Comment by samsonasik** [comment]
closing in favor of #101
