### ISSUE TITLE
remove Null Transport

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#36]
since composer.json master branch is only support php:^7.1

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mail/pull/195

**Comment by michalbundyra** [comment]
Please rebase this against develop and change the target branch. Since it's a BC break, it needs to target a new major version.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mail/pull/195#issuecomment-369737328

**Comment by michalbundyra** [comment]
@weierophinney I've rebased against develop and change target to develop branch.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mail/pull/195#issuecomment-369738376

**Comment by michalbundyra** [comment]
i suppose it addresses problem that `null` is no longer allowed as class names in newer php versions? 

and explanation why it's *removed* not just renamed?


also, fix spelling: `Tranport` -> `Transport`, 

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/195#issuecomment-370810847

**Comment by michalbundyra** [comment]
the `null` transport was mapped to `inMemory`, so, it is same to use `inMemory`. Thank you, I've updated PR title  `Tranport -> Transport,`

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mail/pull/195#issuecomment-370942877

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-mail. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-mail to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-mail.
 - In your clone of laminas/laminas-mail, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mail/pull/195#issuecomment-569994627

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-mail/pull/98 for it.
