### ISSUE TITLE
Drop dependency on zendframework/zend-loader

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#39]
This removes the dependency on the zendframework/zend-load package, as suggested in #185 

The `HeaderLoader` class has been removed and replaced by a simple class map in the `Headers` class.

However, I have also removed the `getPluginClassLoader` and `setPluginClassLoader` methods. Since they are public, this might be a BC break. What do you think?

---

Originally posted by @acelaya at https://github.com/zendframework/zend-mail/pull/186

**Comment by michalbundyra** [comment]
Builds are failing with latest dependencies, but they are failing in master too.

I'll try to figure out how to fix them, but it might take me time.

---

Originally posted by @acelaya at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353377097

**Comment by michalbundyra** [comment]
Please rebase onto develop

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353378080

**Comment by michalbundyra** [comment]
There is a PR with fix, I will merge it shortly

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353378507

**Comment by michalbundyra** [comment]
Perfect then. Thanks.

---

Originally posted by @acelaya at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353378587

**Comment by michalbundyra** [comment]
I have rebased develop. I'll do it again once you merge the other PR.

---

Originally posted by @acelaya at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353380305

**Comment by michalbundyra** [comment]
Just a heads up: there is a big ongoing effort going for next major versions for zend-expressive and related packages as well as for zend-mvc. This change will require a next major version, and I do not expect to get to it until february.

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353385648

**Comment by michalbundyra** [comment]
Ok, no rush :-)

---

Originally posted by @acelaya at https://github.com/zendframework/zend-mail/pull/186#issuecomment-353386743

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-mail. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-mail to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-mail.
 - In your clone of laminas/laminas-mail, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mail/pull/186#issuecomment-569994628

**Comment by samsonasik** [comment]
I've created PR #95 for it.
