### ISSUE TITLE
Transport service factory

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#47]
There is missing service factory for mail transports like same in db and other components.

production config/autoload/local.php

``` php
return [
    'mail' => [
        'transport' => [
            'type'    => 'smtp',
            'options' => [
                'host'              => 'smtp.example.com',
                'connection_class'  => 'login',
                'connection_config' => [
                    'username' => 'no-reply@example.com',
                    'password' => 'xxxxxxxx',
                    'ssl'      => 'tls'
                ],
            ],
        ],
    ],
];
```

testing / dev config/autoload/local.php

``` php
return [
    'mail' => [
        'transport' => [
            'type'    => 'in-memory'
        ],
    ],
];
```

That is may look like https://github.com/autowp/zf-components/blob/master/src/Mail/Transport/TransportServiceFactory.php

---

Originally posted by @autowp at https://github.com/zendframework/zend-mail/issues/120

**Comment by michalbundyra** [comment]
This appears to be at least somewhat implemented in: https://github.com/zendframework/zend-mail/blob/master/src/Transport/Factory.php

---

Originally posted by @fuel-wlightning at https://github.com/zendframework/zend-mail/issues/120#issuecomment-516538753

**Comment by samsonasik** [comment]
there is https://github.com/laminas/laminas-mail/blob/master/src/Transport/Factory.php for that. I am closing it.

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

**Comment by samsonasik** [comment]
I am in mobile, hopefully ok now https://github.com/laminas/laminas-mail/blob/68746105bcf4ca412e2b0e358c3f6f9e7fe933b6/src/Transport/Factory.php
