### ISSUE TITLE
Email Attachments

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#49]
I use Zend in ESPOCRM but i have been having issues with receiving attachments from some users the attachments still remain on the email server but they do not make it in the import any help would be great

this is the error it kicks out in the raw email

Line \"-0700 (PDT)\"does not match header format! 

ESPOcrm 4.2.5
Ubuntu 14.04 LTS 
Apache/2.4.7 (Ubuntu)
Zend 2.5.2 - 2015-09-10

---

Originally posted by @RCFilm at https://github.com/zendframework/zend-mail/issues/114

**Comment by samsonasik** [comment]
you need to provide how you use it in ESPOcrm, also, probably not an issue in this component. I am closing it, please re-create issue with reproducible code and test.
