### ISSUE TITLE
Merging local changes to upstream

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mail#69]
Hello,

I maintain a fork that is used in a mail-related SaaS, and would like to merge those changes upstream for the community to benefit from.  Would you prefer one massive PR with all of these changes, or a PR for each individual change?

You can view those changes at:
https://github.com/ameir/zf2/commits/mail-improvements

Thanks,
Ameir

---

Originally posted by @ameir at https://github.com/zendframework/zend-mail/issues/36

**Comment by michalbundyra** [comment]
One commit per change please.


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-mail/issues/36#issuecomment-155220870

**Comment by michalbundyra** [comment]
*PR


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-mail/issues/36#issuecomment-155220927

**Comment by michalbundyra** [comment]
I began submitting PRs a few days ago, and have a few more to go.  Before ploughing too far forward, are there any questions/concerns about the PRs?  Do you have a timeframe in mind in which they can be reviewed/merged?


---

Originally posted by @ameir at https://github.com/zendframework/zend-mail/issues/36#issuecomment-156594049

**Comment by samsonasik** [comment]
I am closing it. Please re-create a PR with specific improvement you wanted to provide.
