### ISSUE TITLE
Subject encoding depends on the order of setters

### ISSUE THREAD

**Issue by xgin** [laminas/laminas-mail#78]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0

#### Summary

There is some kind of magic behind the encoding of the subject header here: https://github.com/laminas/laminas-mail/blob/004a4a589c8218056cda57e8e94da2cb4cdbfcf3/src/Header/Subject.php#L72
I believe it should work only if I had not specified the encoding explicitly.
But the initial encoding is reset when the value of the subject changes: https://github.com/laminas/laminas-mail/blob/004a4a589c8218056cda57e8e94da2cb4cdbfcf3/src/Header/Subject.php#L89

I would ignore this behavior if only the following case failed: #79 

#### Current behavior / How to reproduce

```
$mail = new Laminas\Mail\Message();
$mail->setSubject('hello world');
$mail->setEncoding('UTF-8');
echo $mail->getHeaders()->get('subject')->getEncoding() . PHP_EOL;
echo $mail->getHeaders()->get('subject')->toString() . PHP_EOL;
```
the code outputs (which is expected):
```
UTF-8
Subject: =?UTF-8?Q?hello=20world?=
```

On the other hand:
```
$mail = new Laminas\Mail\Message();
$mail->setEncoding('UTF-8');
$mail->setSubject('hello world');

echo $mail->getHeaders()->get('subject')->getEncoding() . PHP_EOL;
echo $mail->getHeaders()->get('subject')->toString() . PHP_EOL;
```
this code outputs:
```
ASCII
Subject: hello world
```
The initial UTF-8 encoding is ignored by the subject header in this case.

#### Expected behavior

Both code snippets should return the same result.
If I use `setEncoding` I would expect the usage of the encoding.

**Comment by glensc** [comment]
@xgin:

Never link to branches!
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker

ps: edit your issue to use permalinks
