### ISSUE TITLE
ListParse not work with cyrillic

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#8]
```
dump(
    ListParser::parse(' value="price 1.xlsx"; attribute=""', [';', '=']),
    ListParser::parse(' value="Прайс 2.xlsx"; attribute=""', [';', '='])
);

array:4 [
  0 => " value"
  1 => ""price 1.xlsx""
  2 => " attribute"
  3 => """"
]
array:3 [
  0 => " value"
  1 => ""Прайс 2.xlsx""
  2 => " attribu"
]
```

---

Originally posted by @dimaxz at https://github.com/zendframework/zend-mail/issues/243

**Comment by weierophinney** [comment]
may be

```
        for ($i = 0; $i < $length; $i += 1) {
            //$char = $value[$i];
            $char = substr($value,$i,1);
```

---

Originally posted by @dimaxz at https://github.com/zendframework/zend-mail/issues/243#issuecomment-537469153

**Comment by weierophinney** [comment]
@dimaxz I've tested it on mine and also some server and it works fine in both cases. Looks like it is system dependant issue.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-mail/issues/243#issuecomment-538958275

**Comment by weierophinney** [comment]
Can I send you an email with an attachment so you can read it?

---

Originally posted by @dimaxz at https://github.com/zendframework/zend-mail/issues/243#issuecomment-539427549

**Comment by weierophinney** [comment]
@dimaxz ping me on [zf slack](https://zendframework-slack.herokuapp.com/), please

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-mail/issues/243#issuecomment-539429326

**Comment by weierophinney** [comment]
Failed! invite_limit_reached

---

Originally posted by @dimaxz at https://github.com/zendframework/zend-mail/issues/243#issuecomment-539441713

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
