### ISSUE TITLE
Loops to attach files

### ISSUE THREAD

**Issue by yunluo989** [laminas/laminas-mail#85]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

I need to use loop to attach files 
however i only can do multiple attach files by manual setparts

**Comment by gennadiylitvinyuk** [comment]
Hello @yunluo989 

You can use `addPart()` method in a loop:

```php
$body = new MimeMessage();
$body->setParts([$text, $html]); // $text and $html are defined somewhere above

// And now in loop
$image = new MimePart(fopen($pathToImage, 'r'));
$image->type = 'image/jpeg';
$image->filename = 'image-file-name.jpg';
$image->disposition = Mime::DISPOSITION_ATTACHMENT;
$image->encoding = Mime::ENCODING_BASE64;

$body->addPart($image);

```

**Comment by froschdesign** [comment]
@froschdesign 
See also in the forum: https://discourse.laminas.dev/t/multiple-attachment-with-laminas-mail/2227
