### ISSUE TITLE
Not compatibel with PHP 7.3.16

### ISSUE THREAD

**Issue by michahaesler** [laminas/laminas-mail#87]
### Bug Report

|    Q        |   A
|------------ | ------
| Version  | ^2.10

#### Summary

I try to install the current Version of laminas/laminas-mail with:
`composer require laminas/laminas-mail`

#### Current behavior

But i get the following message:
`This package requires php 7.1 but your PHP version (7.3.16) does not satisfy that requirement.`

#### Expected behavior

Composer installs the package laminas/laminas-mail.

**Comment by Ocramius** [comment]
This package does support 7.3.x:

https://github.com/laminas/laminas-mail/blob/2.10.0/composer.json#L32

Can you paste the full output of the above command?

**Comment by michahaesler** [comment]
Thanks for your feedback.
Below the full output of the command. (My project is still a Zend-Framework project, not Laminas.)
![grafik](https://user-images.githubusercontent.com/26999865/78746436-20605d00-7967-11ea-854b-6b03e4c9b2fa.png)

**Comment by michahaesler** [comment]
Thanks for your help. 
I could solve it.
There was a require: { "php": "7.1" } statement in my projects local composer.json.
