### ISSUE TITLE
Zend mail DKIM failes

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mail#9]
DKIM passed with zend previous versions (als on Magento), now dkim failes when using zend. When using Outlook with same SMTP settings, dkim passes.

### Code to reproduce the issue

    $message = new Message();
            $message->addTo($recipient)
                    ->addFrom(****)
                    ->setSubject('Maintenanceplus - contact')
                    ->setBody($body);
            
            // Send E-mail message (SMTP)
            $transport = new SmtpTransport();
            $options   = new SmtpOptions(array(
                    'name'              => 'maintenanceplus.nl',
                    'host'              => 'mail.maintenanceplus.nl',
                    'port'              => 587,
                    'connection_class'  => 'login',
                    'connection_config' => array(
                        'username' => *,
                        'password' => *
                        'ssl' => 'tls'
                    ),
                ));
            $transport->setOptions($options);
            $transport->send($message);

### Expected results

Mail is send to recipent with passed dkim

### Actual results

dkim failed with zend, but when sending via outlook (same smtp settings) the dkim passes. Also in my Magento webstore the same happens! 

---

Originally posted by @Jilco at https://github.com/zendframework/zend-mail/issues/242

**Comment by weierophinney** [comment]
Some further investigation says that only hotmail has the problem, gmail doesn't fail dkim.

---

Originally posted by @Jilco at https://github.com/zendframework/zend-mail/issues/242#issuecomment-531758137

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
